# Example Workflow: JavaScript/TypeScript Project

# This is a complete CI/CD pipeline for a JavaScript/TypeScript project
# Place this file in: .github/workflows/ci.yml

name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # Lint the codebase
  lint:
    name: Lint Code
    uses: mudman1986/mudman-reusable/.github/workflows/reusable-super-linter.yml@main
    with:
      validate-all-codebase: false
      default-branch: main
      validate-javascript-standard: true
      validate-typescript-standard: true

  # Security scanning with CodeQL
  security:
    name: Security Scan
    uses: mudman1986/mudman-reusable/.github/workflows/reusable-codeql-analysis.yml@main
    with:
      languages: '["javascript"]'
      queries: security-and-quality

  # Review dependencies in pull requests
  dependency-review:
    name: Review Dependencies
    if: github.event_name == 'pull_request'
    uses: mudman1986/mudman-reusable/.github/workflows/reusable-dependency-review.yml@main
    with:
      fail-on-severity: moderate
      fail-on-scopes: runtime

  # Run tests
  test:
    name: Run Tests
    uses: mudman1986/mudman-reusable/.github/workflows/reusable-test-suite.yml@main
    with:
      node-version: '20'
      test-command: npm test
      install-command: npm ci

  # Build and push Docker image (only on main branch)
  docker:
    name: Build Docker Image
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [lint, security, test]
    uses: mudman1986/mudman-reusable/.github/workflows/reusable-docker-build.yml@main
    with:
      image-name: ${{ github.repository }}
      platforms: linux/amd64,linux/arm64
      push: true
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
