# Simple Usage Example

# This file demonstrates the simplest way to use the reusable workflows
# Place this file in: .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Just lint the code
  lint:
    uses: mudman1986/mudman-reusable/.github/workflows/reusable-super-linter.yml@main

  # Just scan for security issues
  security:
    uses: mudman1986/mudman-reusable/.github/workflows/reusable-codeql-analysis.yml@main
    with:
      languages: '["javascript"]'  # Change to match your project

  # Just run tests (customize the test-command)
  test:
    uses: mudman1986/mudman-reusable/.github/workflows/reusable-test-suite.yml@main
    with:
      node-version: '20'            # Or python-version: '3.11'
      test-command: npm test        # Your test command
      install-command: npm ci       # Your install command
